### ISSUE TITLE
cityscapes

### ISSUE THREAD

**Issue by thom966** [PRBonn/PS-res-excite#1]
Is it possible to train the model with Cityscapes?

**Comment by matteosodano** [comment]
Hello, yes it is possible to train with any dataset you want. For doing that, you will need to:
- create the corresponding folder in `src/datasets` following the examples you can find in hypersim and scannet
- add your dataset to `src/datasets/__init__.py`

and you're ready to go.


Pay attention, though, that the proposed network performs RGB-D segmentation, and Cityscapes is a RGB dataset. Thus, you can do two things there:
1. generate and use the disparity image as depth channel - since Cityscapes is stereo. For further details about that, these guys did it: https://github.com/TUI-NICR/ESANet/tree/main
2. use the network as RGB-only by trimming the second encoder (`src/models/model.py`, you can remove the `encoder_depth`).
